name: Feature Request
description: Suggest a new feature
title: '[Feature]: '
labels: ['enhancement']
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: A clear description of the feature you'd like to see.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Why is this needed?
      description: How would this improve ValoraSec?
    validations:
      required: true
